name: Java CI

on: [push, pull_request]

permissions:
  checks: write
  contents: read

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - name: Download WiX
      run: gh release download wix3112rtm --repo wixtoolset/wix3 --pattern 'wix311-binaries.zip'
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Decompress WiX
      run: 7z x wix311-binaries.zip -o".\target\wix" -aoa
    - name: Add WiX to Path
      run: echo "$HOME/target/wix" >> $GITHUB_PATH
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
    - name: Get dependent binaries from cache
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 #v5.0.4
      with:
        path: ./dependencies
        key: swt-jface-lwjgl3zip-tools-windows-v5
    - name: Set up JDK 25
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
      with:
        distribution: 'zulu'
        java-version: 25
    - name: Build with Ant
      run: ant -noinput -buildfile build-windows.xml
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe #v4.3.1
      with:
        check_name: junit-windows
        report_paths: '**/report/TEST-*.xml'
        fail_on_failure: true
        require_passed_tests: true
    - name: Archive windows installer for win32-x64
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
      id: artifact-upload-step1
      with:
        archive: false
        name: LDPartEditor_win32_x64
        path: bin/windows/setup
    - name: Output artifact ID
      run:  echo 'Artifact ID is ${{ steps.artifact-upload-step1.outputs.artifact-id }}'
    - name: Calculate SHA
      run:  gh api /repos/${{ github.repository }}/actions/artifacts/${{ steps.artifact-upload-step1.outputs.artifact-id }} --jq '.digest' > LDPartEditor_win32_x64_sha256_checksum.txt
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Archive checksum
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
      with:
        archive: false
        name: LDPartEditor_win32_x64_sha256_checksum
        path: LDPartEditor_win32_x64_sha256_checksum.txt

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
    - name: Get dependent binaries from cache
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 #v5.0.4
      with:
        path: ./dependencies
        key: swt-jface-lwjgl3zip-tools-linux-v5
    - name: Set up JDK 25
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
      with:
        distribution: 'zulu'
        java-version: 25
    - name: Build with Ant
      run: ant -noinput -buildfile build-linux.xml
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe #v4.3.1
      with:
        check_name: junit-linux
        report_paths: '**/report/TEST-*.xml'
        fail_on_failure: true
        require_passed_tests: true
    - name: Set GDK_BACKEND env variable to x11
      run: sh set_gdk_backend.sh
    - name: Archive linux installer for gtk3-x64
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
      id: artifact-upload-step2
      with:
        archive: false
        name: LDPartEditor_linux_x64
        path: bin/linux-gtk3/setup
    - name: Output artifact ID
      run:  echo 'Artifact ID is ${{ steps.artifact-upload-step2.outputs.artifact-id }}'
    - name: Calculate SHA
      run:  gh api /repos/${{ github.repository }}/actions/artifacts/${{ steps.artifact-upload-step2.outputs.artifact-id }} --jq '.digest' > LDPartEditor_linux_x64_sha256_checksum.txt
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Archive checksum
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
      with:
        archive: false
        name: LDPartEditor_linux_x64_sha256_checksum
        path: LDPartEditor_linux_x64_sha256_checksum.txt

  build-macos-arm:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
    - name: Get dependent binaries from cache
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 #v5.0.4
      with:
        path: ./dependencies
        key: swt-jface-lwjgl3zip-tools-macos-arm-v5
    - name: Set up JDK 25
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
      with:
        distribution: 'zulu'
        java-version: 25
    - name: Build with Ant
      run: ant -noinput -buildfile build-macos-arm.xml
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe #v4.3.1
      with:
        check_name: junit-macos-arm
        report_paths: '**/report/TEST-*.xml'
        fail_on_failure: true
        require_passed_tests: true
    - name: Archive macosx installer for cocoa-x64
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
      id: artifact-upload-step3
      with:
        name: LDPartEditor_mac_arm
        path: bin/macosx/setup
    - name: Output artifact ID
      run:  echo 'Artifact ID is ${{ steps.artifact-upload-step3.outputs.artifact-id }}'
    - name: Calculate SHA
      run:  gh api /repos/${{ github.repository }}/actions/artifacts/${{ steps.artifact-upload-step3.outputs.artifact-id }} --jq '.digest' > LDPartEditor_mac_arm_sha256_checksum.txt
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Archive checksum
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
      with:
        archive: false
        name: LDPartEditor_mac_arm_sha256_checksum
        path: LDPartEditor_mac_arm_sha256_checksum.txt

  build-macos:

    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
    - name: Get dependent binaries from cache
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 #v5.0.4
      with:
        path: ./dependencies
        key: swt-jface-lwjgl3zip-tools-macos-v5
    - name: Set up JDK 25
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
      with:
        distribution: 'zulu'
        java-version: 25
    - name: Build with Ant
      run: ant -noinput -buildfile build-macos.xml
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe #v4.3.1
      with:
        check_name: junit-macos
        report_paths: '**/report/TEST-*.xml'
        fail_on_failure: true
        require_passed_tests: true
    - name: Archive macosx installer for cocoa-x64
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
      id: artifact-upload-step4
      with:
        name: LDPartEditor_mac_x64
        path: bin/macosx/setup
    - name: Output artifact ID
      run:  echo 'Artifact ID is ${{ steps.artifact-upload-step4.outputs.artifact-id }}'
    - name: Calculate SHA
      run:  gh api /repos/${{ github.repository }}/actions/artifacts/${{ steps.artifact-upload-step4.outputs.artifact-id }} --jq '.digest' > LDPartEditor_mac_x64_sha256_checksum.txt
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Archive checksum
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
      with:
        archive: false
        name: LDPartEditor_mac_x64_sha256_checksum
        path: LDPartEditor_mac_x64_sha256_checksum.txt



